version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_app_production

  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rails_user:password@db:5432/budget_app_production

volumes:
  pgdata:
