apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: budget-app-pipeline
spec:
  tasks:
    - name: build-and-push
      taskRef:
        name: build-push-task
    - name: deploy-to-k8s
      runAfter:
        - build-and-push
      taskRef:
        name: deploy-task
